name: Inject Pacific-local scheduled_start

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 AM UTC

jobs:
  inject:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: gem install icalendar tzinfo

      - name: Run injection script
        run: ruby inject_start_times.rb

      - name: Commit updated schedule
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add reign_schedule.json
          git diff --cached --quiet || git commit -m "Inject Pacific-local scheduled_start from .ics"
          git push
